---
title: "Consulting Services"
---

Since 2017 I have worked as an independent statistical consultant, and as a statistician for academic (e.g. Department of Medicine, Western University) and nonprofit community organizations (e.g. The Pediatric Epilepsy Surgery Alliance). Through these experiences I have worked closely with a broad range of clients, providing scientific expertise, and clearly explaining technical concepts and communicating results. I am experienced with a variety of **1) study designs**, including randomized controlled trials, cohort, cross-sectional, and case-control studies, and systematic reviews, and **2) statistical methods**, including generalized linear models, multi-level (mixed) models, growth curve modeling, structural equation modeling, scale development, meta-analytic methods, and unsupervised machine learning. Notably, **I am proficient at conveying technical details clearly and simply in accessible language**. 

I provide individual statistical and methodological consulting services, and can assist with: 

-   Study Design
-   Grant proposal development 
-   Questionnaire design
-   Data Management
-   Data analysis, visualization, and interpretation
-   Scientific manuscript preparation

Please get in touch to inquire about these services and whether I may be able to help with your project. I offer a free consultation to scope the project needs and estimate the cost of the work. 

I have also developed numerous resources designed to introduce trainees to a variety of methodological and statistical topics, as well as a sample size calculator. To access these free resources, click [here](resources.qmd). 


<!-- Contact form  -->
## Get in Touch
<form action="https://formspree.io/f/xoqynave" method="POST">
    <input type="hidden" name="_subject" value="Contact request from kpuka.ca" />
    <input type="email" class="form-control" name="_replyto" placeholder="Your email" required><br>
    <textarea class="form-control" rows="3" name="message" placeholder="Your message" required></textarea><br>
    <button type="submit"class="btn btn-primary">Send</button>
</form>

    
