---
title:  CV/Resume
---


# Education
**PhD**, Epidemiology and Biostatistics, Western University\
**HBSc**, Psychology and Biology, University of Toronto


# Work Experience and Appointments

**_Behavioural Science Fellow_** (2022/11 - Present) <br>
Impact and Innovation Unit, Privy Council Office <br>
Behavioural Science Office, Public Health Agency of Canada <br>
Government of Canada <br>
Toronto, ON <br>

**_Adjunct Research Professor_** (2022/05 - Present) <br>
Department of Medicine, Western University <br>
London, ON <br>

**_Project Scientist_** (2021/03 - 2022/11) <br>
Institute for Mental Health Policy Research, <br>
Centre for Addiction and Mental Health <br>
Toronto, ON <br>

**_Statistician_** (2018/07 - 2021/08) <br>
Department of Medicine, Western University <br>
London, ON <br>
   
**_Methodology and Statistical Consultant_** (2017/01 - 2017/12) <br>
Epidemiology and Biostatistics, Western University <br>
London, ON <br>

**_PhD Candidate_** (2016/09 - 2021/04) <br>
Epidemiology and Biostatistics, Western University <br>
London, ON <br>

**_Clinical Research Project Coordinator_** (2010/12 - 2016/08) <br>
Department of Psychology, Hospital for Sick Children and University of Toronto <br>
Toronto, ON <br>


# Complete Resume:

To download a PDF version of my resume <a href="/files/Klajdi_Puka_Resume.pdf" target="_blank"> please click here</a>. 


# Complete CV:

To download a PDF version of my complete CV <a href="/files/Klajdi_Puka_CV.pdf" target="_blank"> please click here</a>. 


