---
title: Presentations
---

For a complete list of talks and presentations, download my CV <a href="/files/Klajdi_Puka_CV.pdf" target="_blank"> here </a> 

**Socioeconomic Inequalities in Mortality: Decomposing Differential Exposure and Vulnerability to Lifestyle Risk Factors** \
Research Society on Alcoholism 45th Annual Scientific Meeting, Orlando, FL, USA\
June 2022

**Long-term sequelae of childhood-onset epilepsy and epilepsy surgery; Psychiatric and psychosocial outcomes** \
Neuropsychology Special Interests Group, \
American Epilepsy Society Annual Meeting, Seattle, WA, USA\
December 2020


**Neuropsychology and epilepsy - what every clinician treating epilepsy should know in 2020** \
Hot Topics in Epilepsy, \
North American Epilepsy Congress, Toronto, ON, Canada\
September 2020
      

**Cognitive outcomes of pediatric epilepsy surgery** \
Canadian League Against Epilepsy Biennial Conference, Winnipeg, MB, Canada\
September 2019. 


**Childhood-onset epilepsy and long-term child and maternal well-being**\
Paediatric Neuroscience Rounds, Victoria Hospital, London, ON, Canada\
August 2019. 



**Academic achievement and IQ**\
Functional Impacts of Large Resective or Disconnective Pediatric Epilepsy Surgery: Identifying Gaps and Setting Patient-Centered Outcomes Research Priorities, \
The Brain Recovery Project, Cleveland, OH, USA\
August 2019. 
    

**Development and implementation of a long-term population-based study of children with epilepsy**\
Seminar Series, Woolcock Institute of Medical Research, Sydney, NSW, Australia\
November 2018

**Is there functional recovery after pediatric epilepsy surgery? Evidence from cognitive and affective outcomes**\
Epilepsy Surgery Rounds, Toronto Western Hospital, Toronto, ON, Canada\
March 2015


**Feeling smarter, feeling calmer - Can youth hope for such improvements in the long-term after epilepsy surgery?**\
Fellows Talk, University of Toronto, Toronto, ON, Canada\
January 2015
