---
title: Teaching
---

A cornerstone of my teaching philosophy is the alignment of learning outcomes, assessments, and active learning strategies. I take a 'course-long perspective' whereby assignments and activities are designed in relation to each other, each developing skills that are further reinforced by the next task. I also aim to provide opportunities to apply the course material through hands-on components. I strive to provide an engaging and supportive classroom environment through the utilization of various active learning techniques, such polls and games using iClickers/online platforms to review material, debates, and think-pair-share activities. The goal of such activities and classroom discussions is to engender a sense of community, learn from the perspectives of others, and allow for opportunities to apply, analyze, and evaluate during classroom discussions.  


## Western University (London, ON)

### Courses
* 2021 - 2023 <br> 
  Biostatistics 9500: Epidemiology & Biostatistics <br> 
	Graduate Orthodontics & Dentofacial Orthopaedics <br> 
	Schulich School of Medicine & Dentistry, <br>
	Western University <br>    



### Workshops
* July 2019 <br> 
  Data management and analysis using SAS. <br> 
  Epidemiology & Biostatistics 2019 Summer Workshop Series, <br>
	Western University <br>    
  
* May 2018 <br> 
  An applied introduction to analyzing and visualizing interactions in SAS. <br> 
  Epidemiology & Biostatistics 2018 Summer Workshop Series, <br>
	Western University <br>    
  
* Nov 2017 <br> 
  "I have my data! Now what?" SAS basics and data management. <br> 
  Department of Epidemiology & Biostatistics, <br>
	Western University <br>    
  
  
### Certifications Received
* May 2019 <br> 
  Advanced Teaching Program <br> 
  Centre for Teaching and Learning, Western Univesity. <br> 
  Completed a 20-hour course covering topics such as course design strategies, active learning, authentic assessment of student learning, and maintaining a culture of respect and community. 
