<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.538">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Klajdi Puka, PhD - Working with Categorical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QN2NZN1QS3"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QN2NZN1QS3', { 'anonymize_ip': true});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Klajdi Puka, PhD</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">About</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../research.html">Research</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../teaching.html">Teaching</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../consulting.html">Consulting Services</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resources.html">Resources</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../cv.html">CV/Resume</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Working with Categorical Data</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Getting Started</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/data_formatting.html" class="sidebar-item-text sidebar-link">Data Formatting</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/research_proposal.html" class="sidebar-item-text sidebar-link">Research Proposal</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/sample_size_calculator.html" class="sidebar-item-text sidebar-link">Sample Size Calculator</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">R</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/r_intro.html" class="sidebar-item-text sidebar-link">Introduction to R</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/quarto_intro.html" class="sidebar-item-text sidebar-link">Introduction to Quarto</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Clinical Trials</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/rct_design.html" class="sidebar-item-text sidebar-link">Study Design</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/rct_randomization.html" class="sidebar-item-text sidebar-link">Randomization</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/rct_other.html" class="sidebar-item-text sidebar-link">Other Considerators</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Other Study Designs</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/study_case_control.html" class="sidebar-item-text sidebar-link">Case Control</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/study_chart_review.html" class="sidebar-item-text sidebar-link">Chart Review</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/study_pilot_studies.html" class="sidebar-item-text sidebar-link">Pilot Studies</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/study_case_reports.html" class="sidebar-item-text sidebar-link">Case Reports</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/study_systematic_reviews.html" class="sidebar-item-text sidebar-link">Systematic Reviews</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Regressions</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/regression_linear.html" class="sidebar-item-text sidebar-link">Linear Regression</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/regression_logistic.html" class="sidebar-item-text sidebar-link">Logistic Regression</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/regression_survival.html" class="sidebar-item-text sidebar-link">Survival Analyses</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/regression_multilevel.html" class="sidebar-item-text sidebar-link">Multilevel Models</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Other Topics</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/stat_clin_significance.html" class="sidebar-item-text sidebar-link">Statistical vs Clicical Significance</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/confounding.html" class="sidebar-item-text sidebar-link">Confounding</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/categorical_data.html" class="sidebar-item-text sidebar-link active">Categorical Data</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/inter_rater_reliability.html" class="sidebar-item-text sidebar-link">Inter-rater Reliability</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Survey Design</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/surveys_invitation.html" class="sidebar-item-text sidebar-link">Invitation and Follow-up</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../resources/surveys_questions.html" class="sidebar-item-text sidebar-link">Designing Effective Questions</a>
  </div>
</li>
    </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#risk-difference" id="toc-risk-difference" class="nav-link" data-scroll-target="#risk-difference">Risk Difference</a></li>
  <li><a href="#relative-risk" id="toc-relative-risk" class="nav-link" data-scroll-target="#relative-risk">Relative Risk</a></li>
  <li><a href="#odds-ratio" id="toc-odds-ratio" class="nav-link" data-scroll-target="#odds-ratio">Odds Ratio</a></li>
  <li><a href="#relative-risk-rr-vs.-odds-ratio-or" id="toc-relative-risk-rr-vs.-odds-ratio-or" class="nav-link" data-scroll-target="#relative-risk-rr-vs.-odds-ratio-or">Relative Risk (RR) vs.&nbsp;Odds Ratio (OR)</a></li>
  <li><a href="#categorizing-continuous-variables" id="toc-categorizing-continuous-variables" class="nav-link" data-scroll-target="#categorizing-continuous-variables">Categorizing Continuous Variables</a></li>
  <li><a href="#references-and-further-readings" id="toc-references-and-further-readings" class="nav-link" data-scroll-target="#references-and-further-readings">References and Further readings</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Working with Categorical Data</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Topic: The use and interpretations of risk difference (RD), relative risk (RR) and odds ratio (OR) are discussed. Categorization of continuous data is also briefly discussed.</p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The relationship between a binary outcome (e.g.&nbsp;yes vs.&nbsp;no) and other variables may be expressed through risk difference, relative risk and odds ratio. The choice of which effect measure to use is informed by study objectives and study design. These measures are described below and should always be reported with confidence intervals.Logistic regression, a frequently used method to identify the covariates associated with a binary outcome yields odds ratios.</p>
<p>‘Risk’ refers to the probability of having a disease or some outcome. For example, the risks that a single throw of a fair die will produce a six (for example) are 1 to 6, or 1/6.</p>
<p><span class="math display">\[Risk = \frac{\text{number of people with disease/outome}}{\text{total number of people}}\]</span></p>
<p>‘Odds’ refers to the probability that the event of interest occurs to the probability that it does not. For example, the odds that a single throw of a fair die will produce a six (for example) are 1 to 5, or 1/5.</p>
<p><span class="math display">\[Odds = \frac{\text{number of people with disease/outome}}{\text{number of people without disease/outome}} \]</span></p>
<p><strong>Example:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Disease</th>
<th>No Disease</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group A</td>
<td>141</td>
<td>420</td>
<td>561</td>
</tr>
<tr class="even">
<td>Group B</td>
<td>928</td>
<td>13,525</td>
<td>14,453</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>1,063</td>
<td>13,945</td>
<td>15,522</td>
</tr>
</tbody>
</table>
<p>Risk of disease in Group A is 141/561 = 0.25; the odds are 141/420 = 0.33.</p>
<p>Risk of disease in Group B is 928/14,453 = 0.064; the odds are 928/13,525 = 0.069.</p>
<p>This example will continue to be used below.</p>
</section>
<section id="risk-difference" class="level1">
<h1>Risk Difference</h1>
<p>Risk Difference (RD) is the difference between risks:</p>
<p><span class="math display">\[ RD = {\text{Risk of Group A}} - {\text{Risk of Group B}} = \frac{141}{561} -  \frac{928}{14,453} = 0.187 \]</span></p>
<p><strong>Interpretation:</strong> Can convert into a fraction 18.7% = 187/1,000. Patients in Group A had 187 additional cases of disease per 1000 people, compared to patients in Group B.</p>
<p>Alternatively, can report as <strong>number needed to treat (NNT)</strong>. NNT = 1 / RD = 1 / 0.187 = 5.34. Need to treat 5.34 persons with treatment received by Group A to prevent 1 case of the disease.</p>
</section>
<section id="relative-risk" class="level1">
<h1>Relative Risk</h1>
<p>Relative Risk (RR) is the ratio of risks:</p>
<p><span class="math display">\[RR = \frac{\text{Risk of Group A}}{\text{Risk of Group B}} = \frac{141/561}{928/14,453} = 3.91 \]</span></p>
<p><strong>Interpretation:</strong> The risk of disease is 3.91 times higher in Group A, relative to Group B.</p>
<p>Alternatively, can indicate that the risk of disease is 291% (i.e.&nbsp;[3.91 - 1.00] x100%) higher in Group A, relative to Group B.</p>
<p>If the RR is less than 1, (for example RR = 0.256), can indicate that the risk of disease in Group A is 74.4% ([1.00 - 0.256] x 100%) lower, relative to group B.</p>
<p><strong>RR of 1.0 indicates no association</strong>. If the 95% Confidence Interval (CI) of the RR does <strong>not</strong> include the value of 1, this indicates that the difference between groups is statistically significant at p&lt;.05.</p>
</section>
<section id="odds-ratio" class="level1">
<h1>Odds Ratio</h1>
<p>Odds Ratio (OR) is the ratio of the odds:</p>
<p><span class="math display">\[ OR = \frac{\text{Odds of Group A}}{\text{Odds of Group B}} = \frac{141/420}{928/13,525} = 4.89 \]</span></p>
<p><strong>Interpretation</strong>: Similar to RR, but must specify “odds”: The <em>odds</em> of disease are 4.89 times higher in Group A, relative to Group B.</p>
</section>
<section id="relative-risk-rr-vs.-odds-ratio-or" class="level1">
<h1>Relative Risk (RR) vs.&nbsp;Odds Ratio (OR)</h1>
<p><strong>ORs and RRs are not equivalent</strong>. Interpretation of RRs is more intuitive and may be preferred.</p>
<p>The OR will approximate the RR when the prevalence of disease/outcome is low (i.e.&nbsp;&lt;10%). If &gt; 10%, then ORs that are less than 1.0 underestimate the RR, and ORs that are greater than 1.0 overestimate the RR (OR will be more extreme than RR).</p>
<p>RR are appropriate for randomized controlled trials, cohort studies, case-cohort studies, or nested case-control studies. <strong>RRs are not appropriate for traditional case-control studies</strong>. The reason is related to how risk and odds are defined; calculation of risk requires the use of “people at risk” as the denominator. In retrospective (traditional case-control) studies, the total number of exposed people is not available, therefore RR cannot be calculated and OR must be used. Case-control studies are not based on the population, the researcher chooses how many controls to include in the study and this will impact RR but not OR (see example below).</p>
<p>Example: Impact of doubling the control group on the OR and RR.</p>
<div class="columns">
<div class="column" style="width:45%;">
<p>Scenario 1:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Case</th>
<th>Control</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exposed</td>
<td>59</td>
<td><strong>122</strong></td>
<td>181</td>
</tr>
<tr class="even">
<td>Unexposed</td>
<td>48</td>
<td><strong>190</strong></td>
<td>238</td>
</tr>
</tbody>
</table>
<p>OR = (59/48) / (122/190) = 1.91.</p>
<p>RR = (59/181) / (48/238) = 1.68.</p>
</div><div class="column" style="width:10%;">
<!-- empty column to create gap -->
</div><div class="column" style="width:45%;">
<p>Scenario 2 (Control group doubled):</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Case</th>
<th>Control</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exposed</td>
<td>59</td>
<td><strong>244</strong></td>
<td>303</td>
</tr>
<tr class="even">
<td>Unexposed</td>
<td>48</td>
<td><strong>380</strong></td>
<td>428</td>
</tr>
</tbody>
</table>
<p>OR = (59/48) / (244/380) = 1.91.</p>
<p>RR = (59/303) / (48/428)= 1.77.</p>
</div>
</div>
<p>Notice that when the size of the control is doubled, the OR remains unchanged, but the RR changes.</p>
</section>
<section id="categorizing-continuous-variables" class="level1">
<h1>Categorizing Continuous Variables</h1>
<p><strong>Perceived advantage:</strong> simplifies the statistical analysis and leads to easier interpretation and presentation of results</p>
<p><strong>Disadvantages:</strong> A lot of information is lost - variation in the variable is ignored. That is, individuals close to but on opposite sides of the cut point are characterized as being very different rather than very similar Therefore, statistical power to detect a relationship is reduced. Dichotomizing by a median split reduces power by the same amount as would discarding a third of the data!</p>
<p>Therefore, categorizing continuous data is generally discouraged. Although it is not advisable, it may be ideal when there is an underlying dichotomy in the variable, that truly differentiates individuals on different sides of the cut point.</p>
<p>If continuous data is categorized, where should the cut off points be? - Use recognized cut points if they exist, for example define ‘overwight’ as a BMI &gt;25. - Adopt cut points used in previous studies - Using the sample median makes it hard to compare studies. This is because the median value is dependent on the sample, and will be different for every study. - Do not perform several analyses and choose that which gives the most convincing result</p>
</section>
<section id="references-and-further-readings" class="level1">
<h1>References and Further readings</h1>
<p>Altman DG, Royston P. (2006). The cost of dichotomising continuous variables. BMJ, 2006332(7549):1080.</p>
<p>Tripepi, G., Jager, K. J., Dekker, F. W., Wanner, C., &amp; Zoccali, C. (2007). Measures of effect: relative risks, odds ratios, risk difference, and ‘number needed to treat’. Kidney international, 72(7), 789-791.</p>
<p>Bland, J. M., &amp; Altman, D. G. (2000). The odds ratio. BMJ, 320(7247), 1468.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2023, Klajdi Puka
  </li>  
</ul>
    </div>   
  </div>
</footer>



</body></html>